Update CICD.yml

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -43,107 +43,107 @@ jobs:
             echo "VM UUID matches. Proceeding..."
           fi
 
-  # Step 2: Build, Push, Sign, and Get SHA of Docker Image
-  build-and-push:
-    runs-on: [self-hosted, linux-runner]
-    needs: validate-uuid
-    outputs:
-      IMAGE_SHA: ${{ steps.get_image_sha.outputs.IMAGE_SHA }}
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v2
+  # # Step 2: Build, Push, Sign, and Get SHA of Docker Image
+  # build-and-push:
+  #   runs-on: [self-hosted, linux-runner]
+  #   needs: validate-uuid
+  #   outputs:
+  #     IMAGE_SHA: ${{ steps.get_image_sha.outputs.IMAGE_SHA }}
+  #   steps:
+  #     - name: Check out code
+  #       uses: actions/checkout@v2
 
-      - name: Install Docker
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y docker.io
-          sudo systemctl start docker
-          sudo systemctl enable docker
+  #     - name: Install Docker
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install -y docker.io
+  #         sudo systemctl start docker
+  #         sudo systemctl enable docker
 
-      - name: Log in to Docker Hub
-        run: |
-          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+  #     - name: Log in to Docker Hub
+  #       run: |
+  #         echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
-      - name: Build Docker Image
-        run: |
-          sudo docker build -t ${{ secrets.IMAGE_NAME }} .
-          sudo docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
+  #     - name: Build Docker Image
+  #       run: |
+  #         sudo docker build -t ${{ secrets.IMAGE_NAME }} .
+  #         sudo docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
 
-      - name: Push Docker Image to Registry
-        run: |
-          export DOCKER_CONTENT_TRUST=1
-          sudo docker push ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
+  #     - name: Push Docker Image to Registry
+  #       run: |
+  #         export DOCKER_CONTENT_TRUST=1
+  #         sudo docker push ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
 
-      - name: Extract Docker Image SHA256 Digest
-        id: get_image_sha
-        run: |
-          IMAGE_SHA=$(sudo docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} | awk -F'@' '{print $2}')
-          echo "Image SHA256: $IMAGE_SHA"
-          echo "::set-output name=IMAGE_SHA::$IMAGE_SHA"
+  #     - name: Extract Docker Image SHA256 Digest
+  #       id: get_image_sha
+  #       run: |
+  #         IMAGE_SHA=$(sudo docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} | awk -F'@' '{print $2}')
+  #         echo "Image SHA256: $IMAGE_SHA"
+  #         echo "::set-output name=IMAGE_SHA::$IMAGE_SHA"
 
-      - name: Install Cosign for Image Signing
-        run: |
-          wget https://github.com/sigstore/cosign/releases/download/v1.5.2/cosign-linux-amd64
-          chmod +x cosign-linux-amd64
-          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
+  #     - name: Install Cosign for Image Signing
+  #       run: |
+  #         wget https://github.com/sigstore/cosign/releases/download/v1.5.2/cosign-linux-amd64
+  #         chmod +x cosign-linux-amd64
+  #         sudo mv cosign-linux-amd64 /usr/local/bin/cosign
 
-      - name: Debug Image Details
-        run: |
-          echo "Registry: ${{ secrets.DOCKER_REGISTRY_URL }}"
-          echo "Image: ${{ secrets.IMAGE_NAME }}"
-          echo "Tag: ${{ secrets.IMAGE_TAG }}"
-          echo "Cosign Key: ${{ secrets.COSIGN_KEY }}"
+  #     - name: Debug Image Details
+  #       run: |
+  #         echo "Registry: ${{ secrets.DOCKER_REGISTRY_URL }}"
+  #         echo "Image: ${{ secrets.IMAGE_NAME }}"
+  #         echo "Tag: ${{ secrets.IMAGE_TAG }}"
+  #         echo "Cosign Key: ${{ secrets.COSIGN_KEY }}"
 
-      - name: Sign Docker Image with Cosign
-        run: |
-          echo "Signing Image: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}"
-          echo "${{ secrets.COSIGN_KEY }}" > cosign.key
-          cosign sign --key cosign.key "${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}"
+  #     - name: Sign Docker Image with Cosign
+  #       run: |
+  #         echo "Signing Image: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}"
+  #         echo "${{ secrets.COSIGN_KEY }}" > cosign.key
+  #         cosign sign --key cosign.key "${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}"
       
 
-      - name: Install Trivy for Vulnerability Scanning
-        run: |
-          sudo apt-get install -y wget
-          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
-          sudo dpkg -i trivy_0.19.2_Linux-64bit.deb
+  #     - name: Install Trivy for Vulnerability Scanning
+  #       run: |
+  #         sudo apt-get install -y wget
+  #         wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
+  #         sudo dpkg -i trivy_0.19.2_Linux-64bit.deb
 
-      - name: Scan Docker Image with Trivy
-        run: |
-          trivy image ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
+  #     - name: Scan Docker Image with Trivy
+  #       run: |
+  #         trivy image ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
 
-  # Step 3: Validate Image SHA256
-  validate-image:
-    runs-on: [self-hosted, linux-runner]
-    needs: build-and-push
-    steps:
-      - name: Pull Docker Image for Validation
-        run: |
-          export DOCKER_CONTENT_TRUST=1
-          sudo docker pull ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
+  # # Step 3: Validate Image SHA256
+  # validate-image:
+  #   runs-on: [self-hosted, linux-runner]
+  #   needs: build-and-push
+  #   steps:
+  #     - name: Pull Docker Image for Validation
+  #       run: |
+  #         export DOCKER_CONTENT_TRUST=1
+  #         sudo docker pull ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
 
-      - name: Debug Docker Inspect Output
-        run: sudo docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
+  #     - name: Debug Docker Inspect Output
+  #       run: sudo docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
 
-      - name: Validate Pulled Docker Image SHA256
-        run: |
-          PULLED_SHA=$(sudo docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} | awk -F'@' '{print $2}')
-          EXPECTED_SHA="${{ needs.build-and-push.outputs.IMAGE_SHA }}"
+  #     - name: Validate Pulled Docker Image SHA256
+  #       run: |
+  #         PULLED_SHA=$(sudo docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} | awk -F'@' '{print $2}')
+  #         EXPECTED_SHA="${{ needs.build-and-push.outputs.IMAGE_SHA }}"
 
-          echo "Pulled Image SHA256: $PULLED_SHA"
-          echo "Expected Image SHA256: $EXPECTED_SHA"
+  #         echo "Pulled Image SHA256: $PULLED_SHA"
+  #         echo "Expected Image SHA256: $EXPECTED_SHA"
 
-          if [[ "$PULLED_SHA" != "$EXPECTED_SHA" ]]; then
-            echo "Error: Image SHA256 does not match. Aborting."
-            exit 1
-          else
-            echo "Image SHA256 matches. Proceeding..."
-          fi
+  #         if [[ "$PULLED_SHA" != "$EXPECTED_SHA" ]]; then
+  #           echo "Error: Image SHA256 does not match. Aborting."
+  #           exit 1
+  #         else
+  #           echo "Image SHA256 matches. Proceeding..."
+  #         fi
 
-  # Step 4: Next stage (if validation is successful)
-  next-stage:
-    runs-on: [self-hosted, linux-runner]
-    needs: validate-image
-    if: success()
-    steps:
-      - name: Run Next Steps
-        run: echo "Test is Successful. Running next stages..."
+  # # Step 4: Next stage (if validation is successful)
+  # next-stage:
+  #   runs-on: [self-hosted, linux-runner]
+  #   needs: validate-image
+  #   if: success()
+  #   steps:
+  #     - name: Run Next Steps
+  #       run: echo "Test is Successful. Running next stages..."
