Update Docker-Cosign.yaml

diff --git a/.github/workflows/Docker-Cosign.yaml b/.github/workflows/Docker-Cosign.yaml
--- a/.github/workflows/Docker-Cosign.yaml
+++ b/.github/workflows/Docker-Cosign.yaml
@@ -1,4 +1,4 @@
-name: Docker Container as Agenttt
+name: Docker Container as Agent
 on: 
   push: 
     branches: 
@@ -36,6 +36,11 @@ jobs:
       # Step 3: Log in to Docker Hub
       - name: Log in to Docker Hub
         run: |
+          echo "Attempting Docker login"
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_PASSWORD }}" ]; then
+              echo "Error: DockerHub username or password not set."
+              exit 1
+          fi
           echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
       # Step 4: Sign the Container Image (using digest instead of tag)
